version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:2.0
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - PLAINTEXT_HOST://0.0.0.0:9092
  postgres:
    # image: quay.io/debezium/example-postgres:2.0
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  connect:
    build:
      context: ./connect
      dockerfile: Dockerfile
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #    - 8080:8080
  #   links:
  #    - kafka
  #   environment:
  #    - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  #    - KAFKA_CLUSTERS_0_NAME=local
  # transfer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   links:
  #    - kafka
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    links:
     - kafka
     - postgres
